# Generated by Django 5.1.4 on 2024-12-20 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0011_uploadfiles_alter_women_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
